name: Sync Development with Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  sync-development:
    if: github.event.pull_request.merged == true && 
        github.event.pull_request.base.ref == 'main' && 
        github.event.pull_request.head.ref == 'development'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all branch history is fetched

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Switch to Development Branch
        run: |
          git checkout development
          git reset --hard origin/development  # Ensures it's an exact match with remote

      - name: Merge Main into Development
        run: |
          git checkout development
          git merge main --allow-unrelated-histories  # This will force the merge

      - name: Push Changes to Development
        run: git push origin development --force
