name: Sync Development with Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  sync-development:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'development'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into development
        run: |
          git checkout development
          git merge main

      - name: Push changes to development
        run: git push origin development
